name: messagepack_schema
description: MessagePack Schema runtime library.
version: 1.0.0

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0